SERVER_HOSTNAME: localhost:8080
PREFERRED_URL_SCHEME: http
SETUP_COMPLETE: true
SUPER_USERS:
  - quayadmin
CREATE_NAMESPACE_ON_PUSH: true
DATABASE_SECRET_KEY: a8c2744b-7004-4af2-bcee-e417e7bdd235
DB_URI: postgresql://quayuser:quaypass@localhost:5432/quay
DISTRIBUTED_STORAGE_CONFIG:
#  default:
#    - LocalStorage
#    - storage_path: /datastorage/registry
  garage:
    - RadosGWStorage
    - access_key: {{GARAGE_ACCESS_KEY}}
      bucket_name: quaybucket
      hostname: localhost
      is_secure: false
      port: 3900
      region_name: garage
      secret_key: {{GARAGE_SECRET_KEY}}
      storage_path: /datastorage/registry 
DISTRIBUTED_STORAGE_DEFAULT_LOCATIONS: []
DISTRIBUTED_STORAGE_PREFERENCE:
    - garage
FEATURE_MAILING: false
SECRET_KEY: e9bd34f4-900c-436a-979e-7530e5d74ac8
USER_EVENTS_REDIS:
    host: localhost
    port: 6379
BUILDLOGS_REDIS:
    host: localhost
    port: 6379
